#!/bin/bash -v

# Wait for LDAP server to start.
sleep 5

TOADMIN=$(ldapsearch -LLL -x -H ${LDAP_URI} -b ${LDAP_BASE_DN} '(uid=toadmin)' dn)

echo ${TOADMIN}

if [ -z "${TOADMIN}" ]; then
    echo -n "Creating initial LDAP records..."
    pushd toconfigure
    ./configure.d/20-slapd && echo "done."
    popd
fi

# Enable the Apache site and start the web server
cp /totaloffice/examples/apache/totaloffice.conf /etc/apache2/sites-available
a2ensite totaloffice

echo "Starting TotalOffice..."
# toserver for development
bin/toserver 0.0.0.0:8080

# Apache for production
#apache2ctl -D FOREGROUND
